MESSAGE(STATUS "Processing ${CMAKE_CURRENT_LIST_FILE}")
MESSAGE(STATUS "CMAKE SOURCE DIR is: ${CMAKE_SOURCE_DIR}")
MESSAGE(STATUS "CMAKE CURRENT SOURCE DIR is: ${CMAKE_CURRENT_SOURCE_DIR}")

FIND_PATH(HELLO_INCLUDE_DIR hello.h ${CMAKE_SOURCE_DIR}/../t3/install/include/hello)
IF(WIN32)
    FIND_LIBRARY(HELLO_LIBRARY NAMES hello PATHS ${CMAKE_SOURCE_DIR}/../t3/install/staticlib)
ELSEIF(UNIX)
    FIND_LIBRARY(HELLO_LIBRARY NAMES hello PATHS ${CMAKE_SOURCE_DIR}/../t3/install/lib)
ENDIF(WIN32)
    

MESSAGE(STATUS "HEADER IS: " ${HELLO_INCLUDE_DIR})
MESSAGE(STATUS "LIBRARY IS: " ${HELLO_LIBRARY})

IF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
	SET(HELLO_FOUND TRUE)
ENDIF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF(HELLO_FOUND)
	IF(NOT HELLO_FIND_QUIETLY)
		MESSAGE(STATUS "Found Hello: ${HELLO_LIBRARY}")
	ENDIF(NOT HELLO_FIND_QUIETLY)
ELSE (HELLO_FOUND)
	IF(HELLO_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find hello librry")
	ENDIF(HELLO_FIND_REQUIRED)
ENDIF(HELLO_FOUND)
