/**
 * @author moshangcheng
 * @version 1.0
 * @date 2011-8-11 上午10:43:36
 * @brief TopCoder SRM514 C
 * 本题为模拟题，题目给定(hi-lo)不超过1000。
 * 因此通过可以逐个判断每个位置的字符是否为'1'来解决问题。
 * 但是也可以采用缓存避免重复计算，使得当(hi-lo)很大时也能快速计算结果。
 * 此程序使用的就是缓存加速的算法。
 */
#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

const int MAX = 101;
const long long INF = 1000000000000001LL;

long long magicLen[MAX];
long long magicPower[MAX];

class MagicalGirlLevelThreeDivTwo {
public:
	int K;
	vector<string> first;

	long long getMagicLen(int n) {
		if (magicLen[n] != -1) {
			return magicLen[n];
		} else if (n < K) {
			return magicLen[n] = first[n].size();
		} else {
			long long len = 0;
			for (int i = n - 1; i >= 0; i -= K) {
				len += getMagicLen(i);
				if(len > INF) {
					len = INF;
					break;
				}
			}
			return magicLen[n] = len;
		}
	}

	long long getMagicPower(int n) {
		if (magicPower[n] != -1) {
			return magicPower[n];
		} else if (n < K) {
			long long power = 0;
			for (int i = 0; i < first[n].size(); i++) {
				if (first[n][i] == '1') {
					power++;
				}
			}
			return magicPower[n] = power;
		} else {
			long long power = 0;
			for (int i = n - 1; i >= 0; i -= K) {
				power += getMagicPower(i);
			}
			return magicPower[n] = power;
		}
	}

	long long solve(int n, long long lo, long long hi) {
		if (n < K) {
			long long power = 0;
			for (int i = lo; i < hi; i++) {
				if (first[n][i] == '1') {
					power++;
				}
			}
			return power;
		}
		bool flag = false;
		long long cntPower = 0;
		long long cntLen = 0, prevLen = 0;
		for (int i = n - 1; i >= 0; i -= K) {
			prevLen = cntLen;
			cntLen += getMagicLen(i);
			if (cntLen >= hi) {
				if (flag) {
					cntPower += solve(i, 0, hi - prevLen);
				} else {
					cntPower += solve(i, lo - prevLen, hi - prevLen);
				}
				break;
			}
			if (flag) {
				cntPower += getMagicPower(i);
				continue;
			}
			if (cntLen > lo) {
				flag = true;
				cntPower += solve(i, lo - prevLen, cntLen - prevLen);
			}
		}
		return cntPower;
	}

	int theCount(vector<string> first, int n, long long lo, long long hi) {
		this->K = first.size();
		this->first = first;
		fill(magicLen, magicLen + MAX, -1);
		fill(magicPower, magicPower + MAX, -1);
		return solve(n, lo, hi + 1);
	}
};

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, int p1, long long p2, long long p3, bool hasAnswer, int p4) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << p1 << "," << p2 << "," << p3;
	cout << "]" << endl;
	MagicalGirlLevelThreeDivTwo *obj;
	int answer;
	obj = new MagicalGirlLevelThreeDivTwo();
	clock_t startTime = clock();
	answer = obj->theCount(p0, p1, p2, p3);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p4 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p4;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <string> p0;
	int p1;
	long long p2;
	long long p3;
	int p4;

	{
	// ----- test 0 -----
	string t0[] = {"101","01"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 4;
	p2 = 2ll;
	p3 = 5ll;
	p4 = 2;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	string t0[] = {"01","10"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 5;
	p2 = 4ll;
	p3 = 5ll;
	p4 = 1;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	string t0[] = {"1","11","111"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 46;
	p2 = 10000ll;
	p3 = 11000ll;
	p4 = 1001;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	string t0[] = {"0","00","000"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 46;
	p2 = 10000ll;
	p3 = 11000ll;
	p4 = 0;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	string t0[] = {"00110110101101001111101101001011010011111011010010"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 100;
	p2 = 999999999999915ll;
	p3 = 1000000000000000ll;
	p4 = 50;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 5 -----
	string t0[] = {"10000","011011001011000001101000010100000111000110110","000001010001011000001101110","100100000110100001010000","011011010","01100000010101101110000011100011001000","0001010","010011000","000101001","00","1"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 91;
	p2 = 123456ll;
	p3 = 123654ll;
	p4 = 76;
	all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	{
	// ----- test 6 -----
	string t0[] = {"1"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 100;
	p2 = 999999000000000ll;
	p3 = 1000000000000000ll;
	p4 = 1000000001;
	all_right = KawigiEdit_RunTest(6, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING

